export const AUTH_USER='AUTH_USER';
export const AUTH_ERROR ='AUTH_ERROR';
export const SIGN_OUT_USER='SIGN_OUT_USER';
export const NEW_ARTICLE='NEW_ARTICLE';
export const DISPLAY_ARTICLES ='DISPLAY_ARTICLES';